/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
static yyconst short int yy_acclist[270] =
    {   0,
      140,  139,    4,  139,    3,  139,  139,   79,  139,   89,
      139,  139,   81,  139,   60,  139,   61,  139,   56,  139,
       54,  139,   59,  139,   55,  139,   30,  139,   57,  139,
       10,   12,  139,   58,  139,   83,  139,   53,  139,   82,
      139,   65,  139,   65,  139,   65,  139,   65,  139,   91,
      139,   92,  139,  139,   65,  139,   65,  139,   65,  139,
       65,  139,   65,  139,   65,  139,   65,  139,   65,  139,
       65,  139,   65,  139,   65,  139,   65,  139,   65,  139,
       65,  139,   65,  139,   65,  139,   65,  139,   65,  139,
       93,  139,  139,   94,  139,  107,  139,  100,  139,   98,

      139,  139,  117,  139,  110,  139,  108,  139,  139,  128,
      139,  121,  139,  139,  139,  129,  139,  130,  139,  133,
      139,  134,  139,  135,  139,  138,  139,   95,  139,   97,
      139,   96,  139,    4,    2,   86,   70,   72,   90,   68,
       66,   67,   11,   12,   88,   69,   12,   10,   12,   84,
       87,   85,   65,   65,   74,   20,   65,   65,   65,   65,
       65,   65,   65,   65,   37,   39,   40,   65,   44,   65,
       65,   65,   65,   65,   65,   65,   73,  107,   99,  106,
      104,  105,  101,  103,  102,  117,  109,  116,  114,  115,
      111,  113,  112,  128,  120,  127,  119,  125,  126,  122,

      124,  123,  129,  132,  134,  137,   78,   80,   71,   12,
        1,   75,   76,   19,   65,   28,   29,   65,   65,   64,
        5,   43,   65,   65,    7,   65,   48,   65,   65,  118,
      131,  136,   77,   18,   16,    8,   52,   31,   32,   35,
        9,   13,   62,   45,   50,   65,   17,   22,   23,   24,
       25,    6,   27,   14,   63,   46,   15,   49,   51,   65,
       21,   33,   36,   38,   41,   47,   34,   26,   42
    } ;

static yyconst short int yy_accept[314] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    5,    7,    8,   10,   12,   13,   15,   17,   19,
       21,   23,   25,   27,   29,   31,   34,   36,   38,   40,
       42,   44,   46,   48,   50,   52,   54,   55,   57,   59,
       61,   63,   65,   67,   69,   71,   73,   75,   77,   79,
       81,   83,   85,   87,   89,   91,   93,   94,   96,   98,
      100,  102,  103,  105,  107,  109,  110,  112,  114,  115,
      116,  118,  120,  122,  124,  126,  128,  130,  132,  134,
      135,  136,  137,  137,  138,  139,  139,  140,  141,  142,

      143,  144,  145,  146,  147,  148,  150,  150,  150,  150,
      151,  151,  151,  152,  153,  153,  154,  154,  154,  155,
      156,  156,  157,  157,  157,  158,  158,  159,  159,  160,
      161,  161,  162,  163,  163,  164,  165,  166,  166,  167,
      168,  168,  169,  169,  169,  169,  171,  171,  172,  172,
      173,  174,  175,  175,  176,  177,  178,  179,  180,  181,
      182,  183,  184,  185,  186,  187,  188,  189,  190,  191,
      192,  193,  194,  195,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      210,  211,  212,  213,  213,  214,  214,  214,  214,  215,

      215,  215,  215,  215,  216,  216,  216,  216,  217,  219,
      220,  220,  220,  220,  220,  221,  221,  221,  221,  221,
      222,  222,  222,  222,  222,  222,  223,  223,  223,  224,
      224,  224,  225,  227,  228,  228,  229,  230,  231,  232,
      233,  234,  234,  235,  236,  236,  236,  236,  237,  237,
      238,  238,  238,  239,  240,  240,  240,  240,  241,  241,
      241,  241,  241,  242,  243,  243,  243,  244,  245,  245,
      245,  245,  245,  245,  246,  247,  248,  248,  249,  250,
      251,  252,  252,  252,  252,  253,  253,  253,  254,  254,
      255,  255,  256,  257,  258,  258,  259,  261,  262,  262,

      263,  263,  264,  265,  266,  266,  267,  267,  268,  268,
      269,  270,  270
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,    1,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   25,
       23,   23,   23,   23,   23,   23,   23,   26,   23,   23,
       23,   23,   23,   27,   23,   23,   23,   23,   23,   23,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   23,   42,   43,   44,   45,
       46,   47,   23,   48,   49,   50,   51,   23,   52,   53,
       54,   23,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    6,    1,    1,    1,    6,    6,    1,    6,    1,
        6,    1,    6,    1,    1,    1,    1,    6,    1,    6,
        1,    1,    1,    1,    6,    1,    6
    } ;

static yyconst short int yy_base[325] =
    {   0,
        0,    0,   55,   56,   57,   60,   61,   62,   67,   68,
       69,   75,  383,  382,  381,  380,  379,  378,  381,  388,
       78,   90,  359,  373,  357,  356,  367,  388,  388,   62,
      354,  388,   66,  356,   76,   80,  370,   79,   99,   85,
        0,  339,  325,  322,  388,  388,  348,   63,   63,   80,
      331,   71,   84,  324,   84,   69,  333,   70,  317,   86,
       98,  314,  315,   96,  321,  388,  340,  388,    0,  388,
      388,  135,    0,  388,  388,  136,    0,  388,  354,  153,
        0,  388,  350,    0,  388,  352,  388,  388,  388,  138,
      142,  388,  351,  388,  388,  347,  334,  388,  388,  388,

      388,  125,  388,  388,  129,  134,  142,  159,  333,  388,
      173,  347,  388,  388,  331,    0,  308,  305,  298,  388,
      312,  118,  314,  300,  308,  295,  310,  297,  150,  127,
      306,  295,  293,  290,  291,  290,  388,  288,  101,  388,
      290,  284,  149,  144,  289,    0,  282,  289,  151,  279,
      280,  273,  285,  275,  287,  388,    0,  388,  388,  388,
      388,  388,  388,  388,    0,  388,  388,  388,  388,  388,
      388,  388,    0,  317,  388,  388,  388,  388,  388,  388,
      388,  388,    0,  313,    0,  315,  388,  388,  388,  302,
      301,  193,  388,  312,  388,  268,  279,  278,  388,  277,

      268,  271,  268,  277,  272,  259,  257,  388,    0,  268,
      268,  267,  270,  269,  388,  257,  266,  253,  247,  388,
      263,  246,  250,  259,  250,  388,  249,  242,  245,  240,
      249,  236,    0,  388,  243,  245,  241,  388,  388,  388,
      388,  246,  388,  388,  234,  246,  230,  388,  237,  388,
      229,  236,  388,  388,  229,  232,  224,  388,  240,  224,
      221,  234,  388,  388,  226,  219,  388,  388,  211,  222,
      219,  206,  216,  388,  214,  388,  199,  388,  388,  388,
      388,  202,  194,  199,  388,  198,  152,  388,  167,  388,
      143,  388,  388,  388,  120,  388,    0,  388,  113,  388,

      100,  388,  388,  388,   85,  388,   58,  388,   36,  388,
      388,  388,  203,  209,  215,  221,  227,  233,   67,  239,
      245,  251,  257,  263
    } ;

static yyconst short int yy_def[325] =
    {   0,
      312,    1,  313,  313,  314,  314,  315,  315,  316,  316,
      317,  317,  318,  318,  318,  318,  318,  318,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      319,  319,  319,  319,  312,  312,  312,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  312,  312,  312,  320,  312,
      312,  312,  321,  312,  312,  312,  322,  312,  312,  312,
      323,  312,  312,  324,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  319,  312,  312,  319,  312,
      312,  312,  312,  312,  319,  312,  319,  312,  319,  319,
      312,  319,  319,  312,  319,  319,  312,  312,  312,  312,
      312,  319,  312,  312,  312,  319,  312,  319,  312,  319,
      319,  319,  312,  319,  319,  312,  320,  312,  312,  312,
      312,  312,  312,  312,  321,  312,  312,  312,  312,  312,
      312,  312,  322,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  323,  312,  324,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  319,  312,  312,  312,  312,  319,  319,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  319,  312,
      312,  319,  319,  312,  312,  319,  319,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  319,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  319,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,    0,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312
    } ;

static yyconst short int yy_nxt[446] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   41,   42,   43,   44,   45,   20,   46,
       47,   41,   48,   49,   50,   51,   52,   53,   54,   41,
       55,   41,   56,   57,   58,   59,   60,   61,   62,   63,
       41,   64,   41,   65,   66,   67,   68,   70,   70,   74,
       71,   71,   74,   78,   78,   75,   79,   79,   75,   82,
       82,   85,  116,   97,   86,   83,   83,   85,  311,   90,
       86,   90,   98,   72,   72,   76,  100,  101,   76,   80,
       80,   91,  103,   91,  310,  105,  104,  106,  109,  110,

      111,  141,  111,  107,  112,  114,  115,  121,  124,  142,
      125,  122,  126,  130,  123,  144,  107,  309,  147,  113,
      145,  137,  127,  131,  132,  128,  133,  138,  139,  134,
      149,  135,  140,  148,  150,  153,  154,  158,  166,   90,
      159,   90,  102,   91,  167,   91,  102,  219,  107,  105,
      220,  106,  107,  308,  190,  175,  190,  107,  176,  191,
      192,  107,  192,  307,  306,  107,  200,  210,  160,  168,
      107,  201,  161,  169,  111,  211,  111,  305,  112,  162,
      170,  177,  163,  171,  164,  172,  178,  208,  225,  223,
      179,  230,  209,  226,  192,  231,  192,  180,  224,  304,

      181,  303,  182,   69,   69,   69,   69,   69,   69,   73,
       73,   73,   73,   73,   73,   77,   77,   77,   77,   77,
       77,   81,   81,   81,   81,   81,   81,   84,   84,   84,
       84,   84,   84,   20,   20,   20,   20,   20,   20,  157,
      302,  301,  157,  300,  157,  165,  299,  165,  298,  297,
      165,  173,  296,  295,  173,  294,  173,  183,  293,  183,
      292,  183,  183,  185,  291,  290,  185,  185,  185,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,

      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  191,  191,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  229,
      228,  227,  222,  221,  218,  217,  216,  215,  214,  213,
      212,  207,  206,  205,  204,  203,  202,  199,  198,  197,
      196,  195,  194,  193,  189,  188,  187,  186,  184,  174,
      156,  155,  152,  151,  146,  143,  136,  129,  120,  119,
      118,  117,  108,  102,   99,   96,   95,   94,   93,   92,
      312,   89,   89,   88,   88,   87,   87,   19,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312
    } ;

static yyconst short int yy_chk[446] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        3,    4,    6,    7,    8,    5,    7,    8,    6,    9,
       10,   11,  319,   30,   11,    9,   10,   12,  309,   21,
       12,   21,   30,    3,    4,    5,   33,   33,    6,    7,
        8,   22,   35,   22,  307,   36,   35,   36,   38,   38,

       39,   56,   39,   36,   39,   40,   40,   48,   49,   56,
       49,   48,   50,   52,   48,   58,   36,  305,   60,   39,
       58,   55,   50,   52,   53,   50,   53,   55,   55,   53,
       61,   53,   55,   60,   61,   64,   64,   72,   76,   90,
       72,   90,  102,   91,   76,   91,  105,  139,  102,  106,
      139,  106,  105,  301,  107,   80,  107,  106,   80,  107,
      108,  102,  108,  299,  295,  105,  122,  130,   72,   76,
      106,  122,   72,   76,  111,  130,  111,  291,  111,   72,
       76,   80,   72,   76,   72,   76,   80,  129,  144,  143,
       80,  149,  129,  144,  192,  149,  192,   80,  143,  289,

       80,  287,   80,  313,  313,  313,  313,  313,  313,  314,
      314,  314,  314,  314,  314,  315,  315,  315,  315,  315,
      315,  316,  316,  316,  316,  316,  316,  317,  317,  317,
      317,  317,  317,  318,  318,  318,  318,  318,  318,  320,
      286,  284,  320,  283,  320,  321,  282,  321,  277,  275,
      321,  322,  273,  272,  322,  271,  322,  323,  270,  323,
      269,  323,  323,  324,  266,  265,  324,  324,  324,  262,
      261,  260,  259,  257,  256,  255,  252,  251,  249,  247,
      246,  245,  242,  237,  236,  235,  232,  231,  230,  229,
      228,  227,  225,  224,  223,  222,  221,  219,  218,  217,

      216,  214,  213,  212,  211,  210,  207,  206,  205,  204,
      203,  202,  201,  200,  198,  197,  196,  194,  191,  190,
      186,  184,  174,  155,  154,  153,  152,  151,  150,  148,
      147,  145,  142,  141,  138,  136,  135,  134,  133,  132,
      131,  128,  127,  126,  125,  124,  123,  121,  119,  118,
      117,  115,  112,  109,   97,   96,   93,   86,   83,   79,
       67,   65,   63,   62,   59,   57,   54,   51,   47,   44,
       43,   42,   37,   34,   31,   27,   26,   25,   24,   23,
       19,   18,   17,   16,   15,   14,   13,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "first.l"
#define INITIAL 0
#line 2 "first.l"
    #include <stdio.h>
    #include <ctype.h>
    #include <stdlib.h>
    #include <string.h>
    #include "parser.tab.h"
 int lno = 1;
 #define MAX_STR_CONST 256
 char string_buf[MAX_STR_CONST], comment_buf[MAX_STR_CONST];
 char *string_buf_ptr, *comment_buf_ptr;

//Stack Definition
#define Stack_SIZE 100
 void push(); void pop();


    int top = -1;
    int stack_arr[Stack_SIZE];

    void push(int x)
    {
        if (top == Stack_SIZE - 1)
        {

        }
        else
        {
            top = top + 1;
            stack_arr[top] = x;
        }
    }

    void pop()
    {
        if (top == -1)
        {

        }
        else
        {
            top = top - 1;
        }
    }




    #define keyword_size 10
    char keyword[keyword_size];

    int current_indentation = 0;

    int spaces = 0;
    int indentations = 0;

    // string buffer
    #define MAX_STR_CONST 256
    char string_buf[MAX_STR_CONST];
    char *string_buf_ptr;
    ////////////////////
#define DOUBLE_STRING 1

#define SINGLE_STRING 2

#define TRIPLE_STRING 3

#define COMMENT_MULTI 4

#define COMMENT_TRIPLE 5

#define INDENTSTATE 6

#define DEDENTALLSTATE 7

#define DEDENTSTATE 8

#line 687 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 158 "first.l"


#line 841 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 313 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 388 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 160 "first.l"
{
                            BEGIN(INDENTSTATE);
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            push(spaces);

                            current_indentation = spaces;
                            unput(' ');

                            printf("INDENT in line = %d\n",yylineno);
                            return NEWLINE;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 182 "first.l"
{
                            if(top < 0)
                                push(0);

                            spaces = 0;
                            for(int i = 0; i < yyleng; i++){
                                if (yytext[i] == ' ') {
                                    spaces++;
                                } else if (yytext[i] == '\t') {
                                    spaces += 8;
                                }
                            }
                            current_indentation = spaces;

                            unput(' ');
                            BEGIN(DEDENTSTATE);

                            return NEWLINE;
                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 202 "first.l"
{
                            BEGIN(DEDENTALLSTATE);
                            unput(' ');

                            return NEWLINE;
                        }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_STRING):
case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(TRIPLE_STRING):
case YY_STATE_EOF(COMMENT_MULTI):
case YY_STATE_EOF(COMMENT_TRIPLE):
case YY_STATE_EOF(INDENTSTATE):
case YY_STATE_EOF(DEDENTALLSTATE):
case YY_STATE_EOF(DEDENTSTATE):
#line 211 "first.l"
{
                    BEGIN(DEDENTALLSTATE);
                    unput(' ');

                    if(stack_arr[top] == 0)
                        return 0;
                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 221 "first.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 224 "first.l"
{ yylval.str_val = strdup(yytext); return INT_KEYWORD ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 225 "first.l"
{ yylval.str_val = strdup(yytext); return FLOAT_KEYWORD ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 226 "first.l"
{ yylval.str_val = strdup(yytext); return STRING_KEYWORD ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 227 "first.l"
{ yylval.str_val = strdup(yytext); return BOOL_KEYWORD ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 228 "first.l"
{ yylval.str_val = strdup(yytext); return LIST_KEYWORD ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 229 "first.l"
{ yylval.int_val = atoi(yytext); return INT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 230 "first.l"
{yylval.str_val = strdup(yytext); return ARROW ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 231 "first.l"
{ yylval.float_val = atof(yytext); return FLOAT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 232 "first.l"
{ yylval.str_val = strdup(yytext); return MAIN ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "first.l"
{yylval.str_val = strdup(yytext); return MATCH ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 234 "first.l"
{yylval.str_val = strdup(yytext); return RANGE ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 235 "first.l"
{ yylval.str_val = strdup(yytext); return TRUE_TOKEN ;  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 236 "first.l"
{ yylval.str_val = strdup(yytext); return FALSE_TOKEN ;  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 237 "first.l"
{ yylval.str_val = strdup(yytext); return NONE ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 238 "first.l"
{ yylval.str_val = strdup(yytext); return AND ;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 239 "first.l"
{ yylval.str_val = strdup(yytext); return AS ;  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 240 "first.l"
{ yylval.str_val = strdup(yytext); return ASSERT ;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 241 "first.l"
{ yylval.str_val = strdup(yytext); return ASYNC ;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 242 "first.l"
{ yylval.str_val = strdup(yytext); return AWAIT ;  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 243 "first.l"
{ yylval.str_val = strdup(yytext); return BREAK ;  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 244 "first.l"
{ yylval.str_val = strdup(yytext); return CLASS ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 245 "first.l"
{ yylval.str_val = strdup(yytext); return CONTINUE ;  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 246 "first.l"
{ yylval.str_val = strdup(yytext); return INPUT ;  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 247 "first.l"
{ yylval.str_val = strdup(yytext); return DEF ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 248 "first.l"
{ yylval.str_val = strdup(yytext); return DEL ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 249 "first.l"
{ yylval.str_val = strdup(yytext); return DOT ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 250 "first.l"
{ yylval.str_val = strdup(yytext); return ELIF ;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 251 "first.l"
{ yylval.str_val = strdup(yytext); return ELSE ;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 252 "first.l"
{ yylval.str_val = strdup(yytext); return EXCEPT ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 253 "first.l"
{ yylval.str_val = strdup(yytext); return FINALLY ;  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 254 "first.l"
{ yylval.str_val = strdup(yytext); return FROM ;  }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 255 "first.l"
{ yylval.str_val = strdup(yytext); return GLOBAL ;  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 256 "first.l"
{ yylval.str_val = strdup(yytext); return IF ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 257 "first.l"
{ yylval.str_val = strdup(yytext); return IMPORT ;  }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 258 "first.l"
{ yylval.str_val = strdup(yytext); return IN ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 259 "first.l"
{ yylval.str_val = strdup(yytext); return IS ;  }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 260 "first.l"
{ yylval.str_val = strdup(yytext); return LAMDA ;  }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 261 "first.l"
{ yylval.str_val = strdup(yytext); return NONLOCAL ;  }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 262 "first.l"
{ yylval.str_val = strdup(yytext); return NOT ;  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 263 "first.l"
{ yylval.str_val = strdup(yytext); return OR ;  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 264 "first.l"
{ yylval.str_val = strdup(yytext); return PASS ;  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 265 "first.l"
{ yylval.str_val = strdup(yytext); return RAISE ;  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 266 "first.l"
{ yylval.str_val = strdup(yytext); return RETURN ;  }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 267 "first.l"
{ yylval.str_val = strdup(yytext); return TRY ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 268 "first.l"
{ yylval.str_val = strdup(yytext); return WHILE ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 269 "first.l"
{ yylval.str_val = strdup(yytext); return WITH ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 270 "first.l"
{ yylval.str_val = strdup(yytext); return YIELD ;  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 271 "first.l"
{ yylval.str_val = strdup(yytext); return CASE ;  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 272 "first.l"
{ return ASSIGN ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 273 "first.l"
{ yylval.str_val = strdup(yytext); return PLUS ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 274 "first.l"
{ return MINUS ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 275 "first.l"
{ return MULTIPLY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 276 "first.l"
{ return DIVIDE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 277 "first.l"
{return COLON;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 278 "first.l"
{return COMA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 279 "first.l"
{return LEFT_P;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 280 "first.l"
{return RIGHT_P;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 281 "first.l"
{yylval.str_val = strdup(yytext); return NULL_TOKEN;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 282 "first.l"
{yylval.str_val = strdup(yytext); return PRINT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 283 "first.l"
{yylval.str_val = strdup(yytext); return FOR;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 284 "first.l"
{yylval.str_val =strdup(yytext); return ID;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 285 "first.l"
{yylval.str_val=strdup(yytext);return PLUS_ASSIGN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 286 "first.l"
{yylval.str_val=strdup(yytext);return MINUS_ASSIGN;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 287 "first.l"
{yylval.str_val=strdup(yytext);return TIMES_ASSIGN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 288 "first.l"
{yylval.str_val=strdup(yytext);return DIVIDE_ASSIGN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 289 "first.l"
{yylval.str_val=strdup(yytext);return MODULO_ASSIGN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 290 "first.l"
{yylval.str_val=strdup(yytext);return POWER_ASSIGN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 291 "first.l"
{yylval.str_val=strdup(yytext);return AND_ASSIGN;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 292 "first.l"
{yylval.str_val=strdup(yytext);return OR_ASSIGN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 293 "first.l"
{yylval.str_val=strdup(yytext);return XOR_ASSIGN;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 294 "first.l"
{yylval.str_val=strdup(yytext);return LEFT_SHIFT_ASSIGN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 295 "first.l"
{yylval.str_val=strdup(yytext);return RIGHT_SHIFT_ASSIGN;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 296 "first.l"
{string_buf_ptr = string_buf; BEGIN(TRIPLE_STRING);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 298 "first.l"
{ comment_buf_ptr = comment_buf; BEGIN(COMMENT_TRIPLE); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 299 "first.l"
{ string_buf_ptr = string_buf; BEGIN(DOUBLE_STRING); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 300 "first.l"
{ comment_buf_ptr = comment_buf; BEGIN(COMMENT_MULTI); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 301 "first.l"
{ string_buf_ptr = string_buf; BEGIN(SINGLE_STRING); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 306 "first.l"
{ yylval.str_val = strdup(yytext); return GREATER_THAN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 307 "first.l"
{ yylval.str_val = strdup(yytext); return LESS_THAN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 308 "first.l"
{ yylval.str_val = strdup(yytext); return LESS_THAN_OR_EQUAL; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 309 "first.l"
{ yylval.str_val = strdup(yytext); return GREATER_THAN_OR_EQUAL; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 310 "first.l"
{ yylval.str_val = strdup(yytext); return NOT_EQUAL; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 311 "first.l"
{ yylval.str_val = strdup(yytext); return EQUAL; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 312 "first.l"
{ yylval.str_val = strdup(yytext); return FLOOR_DIVISION; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 313 "first.l"
{ yylval.str_val = strdup(yytext); return MODULUS; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 314 "first.l"
{ yylval.str_val = strdup(yytext); return EXPONENTIATION; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 315 "first.l"
{ yylval.str_val = strdup(yytext); return LEFT_BRACKET; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 316 "first.l"
{ yylval.str_val = strdup(yytext); return RIGHT_BRACKET; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 317 "first.l"
{ yylval.str_val = strdup(yytext); return LEFT_CURLY_BRACE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 318 "first.l"
{ yylval.str_val = strdup(yytext); return RIGHT_CURLY_BRACE; }
	YY_BREAK

case 95:
YY_RULE_SETUP
#line 324 "first.l"
{
        BEGIN(INITIAL);
       // printf("INDENT in line = %d\n",yylineno);
        return INDENT;
    }
	YY_BREAK


case 96:
YY_RULE_SETUP
#line 332 "first.l"
{





        int flag = 1;
        for (int i = 0; i <= top; i++) {
            if (current_indentation == stack_arr[i])
                flag = 0;
        }

        if(flag) {
            printf("Indentation Error in line = %d\n",yylineno);
            return INDENT_ERROR;
        }

        int end = 1;
        while(current_indentation < stack_arr[top])
        {
         //   printf("DEDENT in line = %d \n",yylineno);
            unput(' ');
            BEGIN(DEDENTSTATE);
            end = 0;

            pop();

         //   printf("DEDENT in line = %d\n",yylineno);
            return DEDENT;
        }

        if(end)
            BEGIN(INITIAL);

    }
	YY_BREAK


case 97:
YY_RULE_SETUP
#line 371 "first.l"
{
        if (top<0)
            push(0);
        if (stack_arr[top] > 0) {


            while (top > 0) {
                unput(' ');
                BEGIN(DEDENTALLSTATE);
                printf("DEDENT  in line = %d\n",yylineno);
                pop();
                return DEDENT;
            }
        } else {
            BEGIN(INITIAL);
        }
    }
	YY_BREAK


case 98:
YY_RULE_SETUP
#line 395 "first.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;} 
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 396 "first.l"
{              }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 397 "first.l"
{printf("error in line %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 398 "first.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 399 "first.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 400 "first.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 401 "first.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 402 "first.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 403 "first.l"
{*string_buf_ptr++ = '\"';} 
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 404 "first.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK


case 108:
YY_RULE_SETUP
#line 413 "first.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL); return STRING;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 414 "first.l"
{              }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 415 "first.l"
{printf("line%d, ERROR: new line in string\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 416 "first.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 417 "first.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 418 "first.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 419 "first.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 420 "first.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 421 "first.l"
{*string_buf_ptr++ = '\'';} 
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 422 "first.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;        
    }
	YY_BREAK


case 118:
YY_RULE_SETUP
#line 429 "first.l"
{*string_buf_ptr = '\0'; BEGIN(INITIAL);return STRING;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 430 "first.l"
{*string_buf_ptr++ = '\\';}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 431 "first.l"
{*string_buf_ptr = '\n'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 432 "first.l"
{printf("error in line %d\n", lno); lno++; BEGIN(INITIAL);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 433 "first.l"
{*string_buf_ptr++ = '\n';}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 434 "first.l"
{*string_buf_ptr++ = '\t';}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 435 "first.l"
{*string_buf_ptr++ = '\r';}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 436 "first.l"
{*string_buf_ptr++ = '\b';}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 437 "first.l"
{*string_buf_ptr++ = '\f';}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 438 "first.l"
{*string_buf_ptr++ = '\"';}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 439 "first.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *string_buf_ptr++ = *yptr++;
    }
	YY_BREAK


case 129:
YY_RULE_SETUP
#line 448 "first.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *comment_buf_ptr++ = *yptr++;
    }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 453 "first.l"
{ *comment_buf_ptr++ = '\n'; lno++; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 454 "first.l"
{*comment_buf_ptr = '\0';  BEGIN(INITIAL); return COMMENT; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 455 "first.l"
{*comment_buf_ptr++ = '\''; *comment_buf_ptr++ = '\'';}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 456 "first.l"
{*comment_buf_ptr++ = '\'';}
	YY_BREAK


case 134:
YY_RULE_SETUP
#line 459 "first.l"
{
        char *yptr = yytext;
        while ( *yptr )
            *comment_buf_ptr++ = *yptr++;
    }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 464 "first.l"
{ *comment_buf_ptr++ = '\n'; lno++; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 465 "first.l"
{*comment_buf_ptr = '\0';  BEGIN(INITIAL); return COMMENT ;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 466 "first.l"
{*comment_buf_ptr++ = '\"'; *comment_buf_ptr++ = '\"';}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 467 "first.l"
{*comment_buf_ptr++ = '\"';}
	YY_BREAK

case 139:
YY_RULE_SETUP
#line 471 "first.l"
ECHO;
	YY_BREAK
#line 1778 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 313 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 313 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 312);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 471 "first.l"

